name: flutter_launch_arguments
description: "A flutter plugin to retrieve Android and iOS launch arguments"
version: 1.0.1
repository: https://github.com/MyLittleSuite/flutter_launch_arguments
issue_tracker: https://github.com/MyLittleSuite/flutter_launch_arguments/issues
homepage: https://www.mylittlesuite.com

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mylittlesuite.flutter_launch_arguments
        pluginClass: FlutterLaunchArgumentsPlugin
      ios:
        pluginClass: FlutterLaunchArgumentsPlugin
