// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class ArgumentsServicePigeonCodecReader: FlutterStandardReader {
}

private class ArgumentsServicePigeonCodecWriter: FlutterStandardWriter {
}

private class ArgumentsServicePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ArgumentsServicePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ArgumentsServicePigeonCodecWriter(data: data)
  }
}

class ArgumentsServicePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ArgumentsServicePigeonCodec(readerWriter: ArgumentsServicePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ArgumentsService {
  func getString(key: String) throws -> String?
  func getBool(key: String) throws -> Bool?
  func getInt(key: String) throws -> Int64?
  func getDouble(key: String) throws -> Double?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ArgumentsServiceSetup {
  static var codec: FlutterStandardMessageCodec { ArgumentsServicePigeonCodec.shared }
  /// Sets up an instance of `ArgumentsService` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ArgumentsService?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_launch_arguments.ArgumentsService.getString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.getString(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStringChannel.setMessageHandler(nil)
    }
    let getBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_launch_arguments.ArgumentsService.getBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.getBool(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBoolChannel.setMessageHandler(nil)
    }
    let getIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_launch_arguments.ArgumentsService.getInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.getInt(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIntChannel.setMessageHandler(nil)
    }
    let getDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_launch_arguments.ArgumentsService.getDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.getDouble(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDoubleChannel.setMessageHandler(nil)
    }
  }
}
