name: Pipeline

on: push

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Testing
    uses: ./.github/workflows/analyze.yml

  test:
    name: Test ${{ matrix.platform }}
    needs:
      - analyze
    strategy:
      matrix:
        platform: [ android, ios ]
    uses: ./.github/workflows/test.yml
    with:
      platform: ${{ matrix.platform }}

  build:
    name: Build ${{ matrix.platform }}
    needs:
      - test
    strategy:
      matrix:
        platform: [ android, ios ]
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}

  publish:
    name: Publish
    needs:
      - build
    uses: ./.github/workflows/publish.yml